update uad.beneficiarios set usuario_carga='238' where UPPER(usuario_carga)='ADMINISTR';
update uad.beneficiarios set usuario_carga='245' where UPPER(usuario_carga)='ALFREDO A';
update uad.beneficiarios set usuario_carga='264' where UPPER(usuario_carga)='ANDRES GO';
update uad.beneficiarios set usuario_carga='249' where UPPER(usuario_carga)='BETTINA P';
update uad.beneficiarios set usuario_carga='251' where UPPER(usuario_carga)='CAPACITAC';
update uad.beneficiarios set usuario_carga='269' where UPPER(usuario_carga)='CRISTIAN ';
update uad.beneficiarios set usuario_carga='257' where UPPER(usuario_carga)='CRISTIAN ';
update uad.beneficiarios set usuario_carga='256' where UPPER(usuario_carga)='DAIANA MU';
update uad.beneficiarios set usuario_carga='270' where UPPER(usuario_carga)='GABRIEL M';
update uad.beneficiarios set usuario_carga='258' where UPPER(usuario_carga)='GUSTAVO P';
update uad.beneficiarios set usuario_carga='259' where UPPER(usuario_carga)='HELIANA V';
update uad.beneficiarios set usuario_carga='268' where UPPER(usuario_carga)='JAVIER TO';
update uad.beneficiarios set usuario_carga='260' where UPPER(usuario_carga)='JONATHAN ';
update uad.beneficiarios set usuario_carga='255' where UPPER(usuario_carga)='JUAN ALVA';
update uad.beneficiarios set usuario_carga='261' where UPPER(usuario_carga)='JUAN SOTO';
update uad.beneficiarios set usuario_carga='262' where UPPER(usuario_carga)='LEILA BAR';
update uad.beneficiarios set usuario_carga='263' where UPPER(usuario_carga)='LORENA TR';
update uad.beneficiarios set usuario_carga='246' where UPPER(usuario_carga)='LUIS MONT';
update uad.beneficiarios set usuario_carga='248' where UPPER(usuario_carga)='LUIS MONT';
update uad.beneficiarios set usuario_carga='244' where UPPER(usuario_carga)='MARTIN MA';
update uad.beneficiarios set usuario_carga='265' where UPPER(usuario_carga)='PAOLA PAE';
update uad.beneficiarios set usuario_carga='266' where UPPER(usuario_carga)='PATRICIO ';
update uad.beneficiarios set usuario_carga='254' where UPPER(usuario_carga)='PRO BANDO';
update uad.beneficiarios set usuario_carga='247' where UPPER(usuario_carga)='ROBERTO M';
update uad.beneficiarios set usuario_carga='271' where UPPER(usuario_carga)='ROBERTO E';
update uad.beneficiarios set usuario_carga='267' where UPPER(usuario_carga)='RODRIGO S';
update uad.beneficiarios set usuario_carga='243' where UPPER(usuario_carga)='USUARIO C';
update uad.beneficiarios set usuario_carga='250' where UPPER(usuario_carga)='VALERIA Y';
